### ISSUE TITLE
Read/Write Replication: if "all" replication policy is used, adding replicas does not work

### ISSUE THREAD

**Issue by lkairies** [xtreemfs/xtreemfs#226]
_From [michael....@gmail.com](https://code.google.com/u/108462688936989233066/) on November 01, 2011 12:09:02_

The synchronization of a new replica is triggered by reading the first byte from the new replica. If the "quorum" policy is used, the replica reset phase is executed to ensure that the majority of replicas has the latest version. However, the "all" policy allows to skip this step as it assumes that all replicas are always synchronized. In consequence, the objects of the new replica were not copied and the OSD of this replica sees no data for the file. So it believes that the file is empty and will return EOF instead of the actual data.

_Original issue: http://code.google.com/p/xtreemfs/issues/detail?id=226_

**Comment by mikefedyk** [comment]
With 1.5.1 already released, what is the status of this issue?

**Comment by robert-schmidtke** [comment]
@kleingeist are you familiar with this status of this issue by any chance?

**Comment by kleingeist** [comment]
I am currently looking into it. 
As far as i can tell the problem _could_ still occur under certain circumstances. 
The current protocol used for the addition of replicas sends an explicit update request to each replica (and thus also the new one), but it does only wait for the success of a majority. 
So if  the update message to the new replica is somehow lost, the replica could end up in a inconsistent or outdated state. 
Even though this is unlikely to happen, i submitted some changes to the current master branch to address the issue. A small caveat of the patch is the impossibility to change WaR1 replicas if at least one replica is not available. To ensure every replica is consistent and no old data can be read from a removed replica it is necessary to reach them all.
