### ISSUE TITLE
Read/Write Replication: if "quorum" replication policy is used, adding replicas does not work

### ISSUE THREAD

**Issue by lkairies** [xtreemfs/xtreemfs#227]
_From [michael....@gmail.com](https://code.google.com/u/108462688936989233066/) on November 01, 2011 12:20:47_

Due to a bug in the code, adding new replicas to a "quorum" replicated files often does not work at the first attempt. As "xtfsutil" automatically retries to read the first byte of the new replica (which implicitely triggers the synchronization of the new replica), it usually works at the second attempt (after a request timeout, by default 60 seconds).

_Original issue: http://code.google.com/p/xtreemfs/issues/detail?id=227_

**Comment by kleingeist** [comment]
Closed with commit 081c75297a
