### ISSUE TITLE
no OPENSSL_Applink on the Windows Client

### ISSUE THREAD

**Issue by lkairies** [xtreemfs/xtreemfs#314]
_From [grid...@pertino.com](https://code.google.com/u/114789020216117693497/) on April 15, 2014 21:09:35_

What steps will reproduce the problem? 1. Install servers requiring SSL.
2. Install the Windows client 1.5.
3. Try mkfs.xtreemfs with a --pkcs12-file-path argument. What is the expected output? What do you see instead? Expect that it works (as it does on the Mac client).  Instead see

mkfs.xtreemfs -m 777 -u daemon -g staff -d INFO -a NULL -s 64 --pkcs12-file-path C:\fs\Zeus.p12 --pkcs12-passphrase secret fs.example.com/8

Trying to create the volume: fs.example.com/8

Using options:

 Owner:                        daemon

  Owning group:                 staff

  Mode:                         777

  Access Control Policy:        NULL

  Default striping policy:              RAID0

  Default stripe size (object size):    64

  Default stripe width (# OSDs):        1

[ I |  4/14 18:17:59.306 | 668            ] SSL support activated.

[ I |  4/14 18:17:59.494 | 668            ] SSL support using PKCS#12 file C:\fs\Zeus.p12

OPENSSL_Uplink(003D1000,08): no OPENSSL_Applink What version of the product are you using? On what operating system? XtreemFS 1.5 client on Windows 7. Please provide any additional information below and attach client and service log files.

_Original issue: http://code.google.com/p/xtreemfs/issues/detail?id=314_

**Comment by chrkl** [comment]
Support for PKCS12 containers on Windows was removed by commit 259ed2f9b118a56b9e3a6c0ef2b342aa5c9919d4
