### ISSUE TITLE
Java Unit Tests sometimes fail randomly on Travis with 'Port already in use'

### ISSUE THREAD

**Issue by robert-schmidtke** [xtreemfs/xtreemfs#350]
The error is that sometimes for some tests, a specified port is already in use. This does not always happen, and it may happen in different tests during different builds. One example with

'java.net.BindException: Address already in use. Port number: 42639'

can be found at: https://s3.amazonaws.com/archive.travis-ci.org/jobs/42745041/log.txt

**Comment by chrkl** [comment]
Fixed by Pullrequest #367.

**Comment by chrkl** [comment]
This fix was successfully applied in the following Travis job: https://travis-ci.org/xtreemfs/xtreemfs/jobs/46961926
