### ISSUE TITLE
Unable to read file from one OSD, two OSD needed.

### ISSUE THREAD

**Issue by onlyjob** [xtreemfs/xtreemfs#357]
Two ODSs (one local, one remote); replication policy set as follows:

~~~~
xtfsutil /mnt/xtreemfs --set-dsp --replication-policy WaR1 --replication-factor 2
~~~~
and confirmed:
~~~~
Replication policy   WaR1
XLoc version         0
Replicas:
  Replica 1
     Striping policy     STRIPING_POLICY_RAID0 / 1 / 128kB
     OSD 1               63956176-b07a-4d28-abc9-0424c92627b7 (192.168.0.2:32640)
  Replica 2
     Striping policy     STRIPING_POLICY_RAID0 / 1 / 128kB
     OSD 1               1800a1fe-75a2-4312-abec-31a836f5b0cd (192.168.0.204:32640)
~~~~

Reading of file(s) stops when one of two OSD is down (local), resumed when second OSD started... It should be possible to read when only one OSD is up. Confirmed when XtreemFS is mounted in `ro` and `rw` modes.

**Comment by chrkl** [comment]
The problem is the same as described in issue #235.
