### ISSUE TITLE
With the latest debian/jessie services fail to start with the provided default runlevels

### ISSUE THREAD

**Issue by silkentrance** [xtreemfs/xtreemfs#383]
All daemon start scripts define run levels for starting and stopping the xtreemfs services.
These are, for starting, 3 5, and, for stopping, 0 1 2 6, i.e.

```
# Default-Start:    3 5
# Default-Stop:    0 1 2 6
```

With these settings, and using update-rc.d ... defaults, the services will not be started on system boot.

I had to manually change these values to, for starting, 2 3 4 5, and, for stopping, 0 1 6, e.g.

```
# Default-Start:    2 3 4 5
# Default-Stop:    0 1 6
```

After that, the services will be started on system boot.

TIA for fixing this!

**Comment by robert-schmidtke** [comment]
Hi,

I just installed XtreemFS on a fresh installation of Jessie using the following guide: http://www.xtreemfs.org/download_pkg.php with the Wheezy repository and I observed that the services are started accordingly on system boot. Could you detail the steps you took to install XtreemFS? Thanks!

Best
Robert

**Comment by silkentrance** [comment]
I am sorry. I meant debian/wheezy. I thought I had dist-upgraded to jessie but I did not.
