### ISSUE TITLE
xtreemfs user and group will not be created on install (debian/jessie)

### ISSUE THREAD

**Issue by silkentrance** [xtreemfs/xtreemfs#384]
When installing either of the available xtreemfs packages, the xtreemfs user and group will not be created.

It would be nice if that user was created on install instead of manually by the admin.

**Comment by robert-schmidtke** [comment]
Hi,

I just installed XtreemFS on a fresh installation of Jessie using the following guide: http://www.xtreemfs.org/download_pkg.php with the Wheezy repository and I observed that the user is created accordingly. Could you detail the steps you took to install XtreemFS? Thanks!

Best
Robert

**Comment by silkentrance** [comment]
I am sorry, I meant debian/wheezy. I thought I had dist-upgraded the system but I did not.
