### ISSUE TITLE
OSD Farm script not working?

### ISSUE THREAD

**Issue by billylegota** [xtreemfs/xtreemfs#399]
I am trying to setup an XtreemFS installation with three HDDs on a single computer (using xtreemfs-osd-farm) with a second computer acting as the DIR and MRC. However, when I tried to test the setup only one of the OSDs from the OSD farm actually showed up when I used xtfsutil on the mount point. 

Why is this occurring?

 I have made sure that there is no firewall and that the computers can communicate. I have also made sure that all of the OSDs are running (when I type xtreemfs-osd-farm status it shows that all three OSDs are running but they do not show up when using xtfsutil on the server).

Thank you for your time.

**Comment by chrkl** [comment]
Could you please check if all of your OSD configurations contain a unique UUID string?

**Comment by billylegota** [comment]
That worked, thanks! I just used uuidgen to make a new UUID for all the configs. You should consider adding a note about that in the documentation; it trips up newbies like me :)
