### ISSUE TITLE
Xtreemfs Cannot Work behind NAT

### ISSUE THREAD

**Issue by alex8224** [xtreemfs/xtreemfs#400]
I study xtreemfs guide and build datastore base xtreemfs. It have many good feature. 
But I was found one problem that xtreemfs can not work behind NAT. 
In user's guide. It suggesting that add new eth device and bind a external ip address on it. But In some country. IP Address is a  scarce resource. So, service must be worked behind NAT without external ip address, only port mapping.
In the future, may Xtreemfs  make some changes in this Scenario?

**Comment by chrkl** [comment]
You can use the hostname parameter of the DIR and MRC service. Setting this to the public addresses of your services, let register them correctly at the DIR. See section 3.2 of the user guide for details: http://xtreemfs.org/xtfs-guide-1.5.1/index.html#tth_sEc3.2

**Comment by alex8224** [comment]
Ok, It also worked on dir/mrc replication?

**Comment by chrkl** [comment]
Currently not. This is a known bug and will not be fixed, as we plan a rewrite of the DIR/MRC replication.

**Comment by alex8224** [comment]
Ok. Tks

Christoph Kleineweber <notifications@github.com>于2015年8月7日周五 下午5:50写道：
