### ISSUE TITLE
broken link in user guide

### ISSUE THREAD

**Issue by jan--f** [xtreemfs/xtreemfs#438]
Link to ACL docu is broken.
http://www.xtreemfs.org/xtfs-guide-1.5.1/index.html#tth_sEc5.3.5

**Comment by jan--f** [comment]
I think we can substitute this link:
https://doc.opensuse.org/documentation/html/openSUSE_121/opensuse-security/cha.security.acls.html

Any objections @chrkl , @robert-schmidtke ?

**Comment by robert-schmidtke** [comment]
@jan--f haven't had the chance to check the contents of the documentation the current link points to, but looks good to me. is there a less openSUSE version specific URL, i.e. something that always points to "latest"? I checked that openSUSE_122 is the latest documentation in their old system, from 13.1 they moved to another documentation server: https://doc.opensuse.org/ (currently down for maintenance though). should we point to the latest release (13.2 if I'm not mistaken)?

**Comment by jan--f** [comment]
alternatively we could link to the man pages..its a more techincal discussion.
http://man7.org/linux/man-pages/man5/acl.5.html

**Comment by jan--f** [comment]
Closing due to age.
