### ISSUE TITLE
pkcs12-file-path option ignored under -o for xtreemfs.mount

### ISSUE THREAD

**Issue by juur** [xtreemfs/xtreemfs#443]
If you compare these two command lines and results. For some reason, in the latter case the SSL options are not getting passed and/or the pbrpcs:// prefix is being ignored?

`/sbin/mount.xtreemfs pbrpcs://xtreemfs-test-1.localnet/myVolume /mnt -o rw,_netdev,log-level=DEBUG, --pkcs12-file-path=/etc/xos/xtreemfs/truststore/certs/client_ca.p12`

> [ D |  7/23 10:32:07.953 | 7f98c2020840   ] Created a new libxtreemfs Client object (version 1.5.1 (Wonderful Waffles))
[ I |  7/23 10:32:07.953 | 7f98c2020840   ] **SSL support activated**.
[ I |  7/23 10:32:07.953 | 7f98c2020840   ] SSL support using PKCS#12 file /etc/xos/xtreemfs/truststore/certs/client_ca.p12
[ I |  7/23 10:32:07.956 | 7f98c2020840   ] Writing 1 verification certificates to /tmp/can2fbnR
[ D |  7/23 10:32:07.956 | 7f98c2020840   ] tmp file name:/tmp/pmNaiH9q /tmp/ctDyvdW0
[ D |  7/23 10:32:07.964 | 7f98bc233700   ] Starting RPC client.
[ D |  7/23 10:32:07.964 | 7f98bc233700   ] Running in SSL mode.

`/sbin/mount.xtreemfs pbrpcs://xtreemfs-test-1.localnet/myVolume /mnt -o rw,_netdev,log-level=DEBUG,pkcs12-file-path=/etc/xos/xtreemfs/truststore/certs/client_ca.p12`

> [ D |  7/23 10:32:20.022 | 7f2d70973840   ] Created a new libxtreemfs Client object (version 1.5.1 (Wonderful Waffles))
[ D |  7/23 10:32:20.022 | 7f2d6ab86700   ] Starting RPC client.

**Comment by robert-schmidtke** [comment]
Are you running the stable 1.5.1 version? If so, have a look at #372 where we introduced a fix in the unstable packages of XtreemFS: http://download.opensuse.org/repositories/home:/xtreemfs:/unstable/

**Comment by juur** [comment]
Yes this is stable, I don't really want to run an unstable branch in production. I will wait for a new production release and then re-test. Thank you.

**Comment by robert-schmidtke** [comment]
Note that the unstable packages mostly contain fixes to issues that were reported along the line. We're currently preparing a 1.6 release that incorporates these fixes and some new features, but you're welcome to try the 'preview' packages as well.
