### ISSUE TITLE
Linux kernel client?

### ISSUE THREAD

**Issue by mtbar131** [xtreemfs/xtreemfs#458]
Does xtreemfs have a Linux kernel client? If not, is there any plan of adding it?

**Comment by robert-schmidtke** [comment]
I'm not sure I understand what you mean by Linux kernel client, could you please clarify? What do you want to achieve?

**Comment by mtbar131** [comment]
If want to use xtreemfs as an underlying filesystem for my linux server, how can I achieve that? 
Something like this [Ceph client](https://github.com/ceph/ceph-client)

**Comment by robert-schmidtke** [comment]
You can currently mount XtreemFS regularly via FUSE and also via fstab, check the [User Guide](http://www.xtreemfs.org/xtfs-guide-1.5.1/index.html#tth_sEc4.3). There are no extensions planned to that.

**Comment by mtbar131** [comment]
Thanks. I was actually just looking for a contribution opportunity in xtreemfs. (I wanted to do a contribution to xtreemfs as a part of my semester-long project)

**Comment by mikefedyk** [comment]
You might actually write that in the issue in the first place.

**Comment by mtbar131** [comment]
@mikefedyk .Yeah, I didn't ask because I was not sure if it was okay to ask that in issues. Anyway, are there any such contribution opportunities which can be taken as a semester-long project?

**Comment by mikefedyk** [comment]
No idea.  Try asking in a new issue.  Look for TODO somewhere and don't
make it a huge idea, just something you can do in a month.  It'll take the
rest of the time refactoring and testing.

**Comment by robert-schmidtke** [comment]
There are currently no such plans that we could give away as tasks for research at the moment. You are free, however, to fork XtreemFS and implement some feature yourself. We're happy to receive PRs any time. But since this is not an issue, you're right, conversation via the mailing list is preferred.
