### ISSUE TITLE
Won't compile on debian stretch (9.x) and no packages avaliable

### ISSUE THREAD

**Issue by jsalatiel** [xtreemfs/xtreemfs#465]
Just opening the issue to let people know.
here the message i got from the maillist.

>Hi,
>
>I have added the Debian 9.0 repository to our build service, unfortunately it fails building:
>https://build.opensuse.org/package/live_build_log/home:xtreemfs:unstable/xtreemfs-testing>>/Debian_9.0/x86_64
>
>There appear to be changes in OpenSSL 1.1.0 that break the build in rpc/client.cpp, e.g. here:
>https://github.com/xtreemfs/xtreemfs/blob/master/cpp/src/rpc/client.cpp#L360
>
>I imagine there is a different accessor function to get the 'error' field out of 'sctx' now. One would >need to resarch what the minimum OpenSSL version was that introduced this change, and then add >proper #ifdefs in the code, using sctx->error in the old version, and error = X509_??? in the new >version.
>It would probably be best to write a function or Macro that returns the error, depending on the >OpenSSL version used during compilation.
>
>Unfortunately, right now I don't have the time to do this, and I'm not sure when I'll get to it.
>
>Are you comfortable with C++? If so, we'd greatly appreciate if you set up a VM with Stretch, fork >XtreemFS from GitHub (https://github.com/xtreemfs/xtreemfs) and try and build it with the OpenSSL >fixes as described above (simply clone the repo and then 'make client server' to build XtreemFS). >You can then open a PR and we'll happily merge it after review.
>In any case, could you please open an issue on GitHub for this? Many thanks!
>
>Cheers
>Robert

**Comment by robert-schmidtke** [comment]
http://download.opensuse.org/repositories/home:/xtreemfs:/unstable/Debian_9.0/
