### ISSUE TITLE
DIR/MRC-Replication: Please Update Documentation

### ISSUE THREAD

**Issue by mwaeckerlin** [xtreemfs/xtreemfs#471]
First of all, congratulation: XtreemFS is in my first tests 40-280 times faster than GlusterFS, even with OSD distribution to a remote host with a little latency. But unfortunately, I failed setting up DIR/MRC-Replication. I do not know if it is a software issue or I just don't understand the documentation. In the latter case, I suggest improving the guide. I would like to help you improving it, since the software looks great.

My Steps
====

I followed the instruction on [6.3  MRC and DIR Replication](http://www.xtreemfs.org/xtfs-guide-1.5.1/index.html#tth_sEc6.3), but neither DIR nor MRC are replicated. OSD-Replication works out of the box.

Open Questions in Documentation
----

One important question that was not clear from the documentation:
- Is there a special master node (the one that is specified as default directory server) which is setup differently, or are all nodes equal?
  - is this the same in DIR and MRC
- Does the word «replica» mean the replicating clients with or without the master node?
- Does the text «Enable the replication plug-in on all replicated MRC/DIR instances» mean: all instances except the master, only the replicas? → This is my understanding

My problem: I tried both configurations, both failed:
- If I enable the replication plug-in on master, it is not replicated
- If I do not enable the replication plug-in on master, the services crash after a while (10-20min)

[Edit: Now it is clear: All nodes are equal, but they must be started at the same time, otherwise the services fail. → Please add this information to the documentation.]

Other questions:
- Should the value of `babudb.repl.sync.n` always be half of the number of all nodes plus one, rounded up?
  - If yes, why can I configure it? The software should calculate the number automatically.

Problems
----

- On Ubuntu 16.04, there should be configuration files for `systemctl`, not `/etc/init.d`
- The services often just crash (quit with different error messages, e.g. «not found giving up») — a server process should never terminate
  - Crashed servers are in status (`systemctl status`): `Active: active (exited)`
- When a server process exits, it should be restarted automatically. This should be part of the `systemctl` or `/etc/inittab`startup configuration

Suggestions
----

- Step by step how to instructions or quick tutorial for:
  - If you have one master DIR/MRC server, how to add the first replication client node
 - How to add additional replica nodes
 - How to remove a replica node for OSD/DIR/MRC

My Configuration
====

I described all the steps I executed on my blog: [Evaluation of Distributed Filesystems for Docker Swarm](https://marc.wäckerlin.ch/computer/evaluation-of-distributed-filesystems-for-docker-swarm#Installation)

I have one master node, named `universum` and (currently) two client nodes named `urknall` and `raum` there is another spare server name `pulsar`ready to join the team (it is a bit slower, so I didn't include it yet).

Update
====

I got it, now it works. Probably the problem was that I was setting up and starting one server after the other, instead of setting all up, then starting all at once.

It seems, that if you to not startup all nodes at the same time, services stop working and then they are not restarted, but remain in status `Active: active (exited)`.

**→ This is a problem that should be fixed!** Services should wait forever for their partners and never terminate, or at least automatically restart if they are in an inconsistent state.

**Comment by mwaeckerlin** [comment]
Still a problem: I crated a volume, but the volume is only shown on the website of the master http://universum:30636/, but it is missing e.g. on the client http://urknall:30636/ — so the MRC are not replicated?

Please add a new howto: Hot to check for the replication status and whether replication is working?

**Comment by robert-schmidtke** [comment]
As mentioned in #472, DIR/MRC replication is an experimental feature with issues that we are aware of during failover. That being said let me comment on your questions.

> Should the value of babudb.repl.sync.n always be half of the number of all nodes plus one, rounded up?

If you want to ensure data safety, you will always need to specify a majority. This could be n/2 + 1 or a value higher than that.

> On Ubuntu 16.04, there should be configuration files for systemctl, not /etc/init.d

You're right, this is legacy. However I doubt we'll be changing this as part of XtreemFS's future. Note this is mainly is a research project with different people working on it with improving different parts. Keeping up with deployment options is not a top priority in this case, I'm afraid to say.

> Services should wait forever for their partners and never terminate, or at least automatically restart if they are in an inconsistent state.

Yes you're right. At the moment this is a hardcoded value and should be configurable (also for retrying infinitely).

Thank you for reporting these issues in such detail. However I cannot make any promises as to when/whether they will be addressed, as major architectural changes will be involved, and we currently do not have people working on XtreemFS full-time.

**Comment by mwaeckerlin** [comment]
Do I understand right: Without DIR/MRC replication, there is still a single point of failure, where you can loose all data? Isn't redundancy and fail over a core feature?

I switched to LizardFS.
