### ISSUE TITLE
Ubuntu 16.04 APT key has expired

### ISSUE THREAD

**Issue by TomCrypto** [xtreemfs/xtreemfs#484]
```
$ apt-key list
pub   1024D/2FA7E736 2008-05-20 [expired: 2018-07-04]
uid                  home:xtreemfs OBS Project <home:xtreemfs@build.opensuse.org>
```

We are using this repository:

```http://download.opensuse.org/repositories/home:/xtreemfs/xUbuntu_16.04```

As you can see the key expired yesterday. Can the key be renewed please? Thanks.

**Comment by TomCrypto** [comment]
Thanks for the quick reply.

**Comment by robert-schmidtke** [comment]
As we're having issues with our build service, I cannot say when I can come back to this. Feel free to use the 1.6.x repository at https://download.opensuse.org/repositories/home:/xtreemfs:/1.6.x/xUbuntu_16.04/
Sorry for that, at the moment we don't have the capacity to address this issue in detail.

**Comment by stig-kristiansen** [comment]
One year later and the key is still expired. I guess this means the project is dead.

What happened? No developers to maintain this?

**Comment by robert-schmidtke** [comment]
Hi @stig-kristiansen, thanks for your reminder. As stated in previous answers and guessed by yourself, the project is not being actively developed, and we have not had the resources to look into the build service. Thanks for understanding.
