### ISSUE TITLE
Code Migration

### ISSUE THREAD

**Issue by giorgiozoppi** [xtreemfs/xtreemfs#491]

**Comment by robert-schmidtke** [comment]
Afaik there are no plans whatsoever of migrating any part of the codebase to another language.

**Comment by giorgiozoppi** [comment]
and if there were, where would you start?

**Comment by robert-schmidtke** [comment]
I'm not part of the project anymore, so I won't recommend anything here. As this is a research project, I'm not sure about any plans going forward. If you really want to contribute, you can always fork. I see you've already texted the mailing list, which is exactly the right place to ask :) Please bear in mind there might be limited resources available (if at all), so do take no harm if your request ends up not being processed.
