### ISSUE TITLE
Is the project still alive?

### ISSUE THREAD

**Issue by gnh1201** [xtreemfs/xtreemfs#500]
Hello. When I was a high school student ten years ago, I learned about distributed file systems through XtreemFS and have some memories of setting it up. Of course, there are newer storage technologies available in the world now, but I still think traditional distributed file systems have their merits, and it brings back old memories, so I came back here.

However, it seems like the project is not active. The resources that used to exist appear to be inaccessible.

Is this project still alive? Or should I explore something like Ceph?

**Comment by gnh1201** [comment]
Oh, I'm really sorry. I got the date wrong. It wasn't ten years ago, but six years ago. I was a college student back then. :)

**Comment by schintke** [comment]
Hi. At the moment, there is no active maintenance, development, or third-party contribution happening or planned. That is correct.
