### ISSUE TITLE
User and group quota support

### ISSUE THREAD

**Issue by lkairies** [xtreemfs/xtreemfs#76]
_From [Minor.Go...@gmail.com](https://code.google.com/u/107492859910690119211/) on October 26, 2009 13:10:27_

usrquota and grpquota options passed to FUSE in /etc/fstab. Possible to
implement this ourselves?

_Original issue: http://code.google.com/p/xtreemfs/issues/detail?id=76_

**Comment by rbaerzib** [comment]
Volume, user and group quota support has been implemented.
